global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'coordinator-node'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['coordinator-node:8080']

  - job_name: 'mining-pool'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']