apiVersion: v1
kind: Service
metadata:
  name: nodepool-internal
  namespace: apps
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.11
  selector:
    app: node-pool
  ports:
    - name: http
      port: 8081 
      targetPort: 8081
      protocol: TCP