apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockchain-sa
  namespace: apps
  annotations:
    iam.gke.io/gcp-service-account: python-miner-sa@majestic-stage-484717-f5.iam.gserviceaccount.com